### PR TITLE
+media codecs

### PR DESCRIPTION
**Pull request by fastrizwaan**
LD_LIBRARY_PATH needed for libffmpeg.so to work

### CODE REVIEW

**Comment by fastrizwaan** [comment]
i'll add another one with widevine

**Comment by snugglej** [comment]
Okay thanks for doing that I'll accept the commit after I test it. Appreciate you helping out.

**Comment by snugglej** [comment]
@fastrizwaan, I was wondering if you knew what is the difference between LD_PRELOAD and LD_LIBRARY_PATH. Are they both needed?

I was taking the vivaldi script that they use and playing off that with LD_PRELOAD but your LD_LIBRARY_PATH environment variable works. So Should I just update the vivaldi shell script to set that instead of LD_PRELOAD or are both needed?

**Comment by fastrizwaan** [comment]
LD_LIBRARY_PATH loads .so files from shared library directories. I think it should work **without** LD_PRELOAD. Please test once.

**Comment by snugglej** [comment]
I looked up ld.so man file and it makes sense. 

I'm going to try building LD_LIBRARY_PATH into my launch script and see if it will work also.

>              A list of directories in which to search for ELF libraries
>               at execution time.  The items in the list are separated by
>               either colons or semicolons, and there is no support for
>               escaping either separator.  A zero-length directory name
>               indicates the current working directory.

Looks like I can also dynamically specify the path:

>               library to be searched for in either the lib or lib64 subdirectory
>               below the directory containing the program to be executed:
> 
>                   $ LD_LIBRARY_PATH='$ORIGIN/$LIB' prog

**Comment by fastrizwaan** [comment]
we have already provided LD_LIBRARY_PATH ennvironment in flatpak manifest
`  "--env=LD_LIBRARY_PATH=/app/var/opt/vivaldi/media-codecs-89.0.4389.90/:/app/var/opt/vivaldi/lib/`

we don't need to provide that LD_LIBRARY_PATH again anywhere in any script.

**Pull request closed without merging**
